# coding: utf-8

"""
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self


class NotificationEmailSettingsOptions(BaseModel):
    """
    NotificationEmailSettingsOptions
    """  # noqa: E501

    email_from: Optional[StrictStr] = Field(default=None, alias="emailFrom")
    sender_name: Optional[StrictStr] = Field(default=None, alias="senderName")
    smtp_host: Optional[StrictStr] = Field(default=None, alias="smtpHost")
    smtp_port: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="smtpPort"
    )
    secure: Optional[StrictBool] = None
    ignore_tls: Optional[StrictBool] = Field(default=None, alias="ignoreTls")
    require_tls: Optional[StrictBool] = Field(default=None, alias="requireTls")
    auth_user: Optional[StrictStr] = Field(default=None, alias="authUser")
    auth_pass: Optional[StrictStr] = Field(default=None, alias="authPass")
    allow_self_signed: Optional[StrictBool] = Field(
        default=None, alias="allowSelfSigned"
    )
    __properties: ClassVar[List[str]] = [
        "emailFrom",
        "senderName",
        "smtpHost",
        "smtpPort",
        "secure",
        "ignoreTls",
        "requireTls",
        "authUser",
        "authPass",
        "allowSelfSigned",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationEmailSettingsOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if auth_user (nullable) is None
        # and model_fields_set contains the field
        if self.auth_user is None and "auth_user" in self.model_fields_set:
            _dict["authUser"] = None

        # set to None if auth_pass (nullable) is None
        # and model_fields_set contains the field
        if self.auth_pass is None and "auth_pass" in self.model_fields_set:
            _dict["authPass"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationEmailSettingsOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "emailFrom": obj.get("emailFrom"),
                "senderName": obj.get("senderName"),
                "smtpHost": obj.get("smtpHost"),
                "smtpPort": obj.get("smtpPort"),
                "secure": obj.get("secure"),
                "ignoreTls": obj.get("ignoreTls"),
                "requireTls": obj.get("requireTls"),
                "authUser": obj.get("authUser"),
                "authPass": obj.get("authPass"),
                "allowSelfSigned": obj.get("allowSelfSigned"),
            }
        )
        return _obj
