# coding: utf-8

"""
listrr.pro V1

An extensive API for working with listrr.pro

The version of the OpenAPI document: v1
Contact: developers@listrr.pro
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ListrrContractsEnumControllersListControllerShowListSortEnum(str, Enum):
    """
    ListrrContractsEnumControllersListControllerShowListSortEnum
    """

    """
    allowed enum values
    """
    NAME = "Name"
    RELEASEDATE = "ReleaseDate"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ListrrContractsEnumControllersListControllerShowListSortEnum from a JSON string"""
        return cls(json.loads(json_str))
