# coding: utf-8

"""
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.overseerr.models.user_user_id_quota_get200_response_movie import (
    UserUserIdQuotaGet200ResponseMovie,
)


class TestUserUserIdQuotaGet200ResponseMovie(unittest.TestCase):
    """UserUserIdQuotaGet200ResponseMovie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUserIdQuotaGet200ResponseMovie:
        """Test UserUserIdQuotaGet200ResponseMovie
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserUserIdQuotaGet200ResponseMovie`
        """
        model = UserUserIdQuotaGet200ResponseMovie()
        if include_optional:
            return UserUserIdQuotaGet200ResponseMovie(
                days = 7,
                limit = 10,
                used = 6,
                remaining = 4,
                restricted = False
            )
        else:
            return UserUserIdQuotaGet200ResponseMovie(
        )
        """

    def testUserUserIdQuotaGet200ResponseMovie(self):
        """Test UserUserIdQuotaGet200ResponseMovie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
