# coding: utf-8

"""
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.overseerr.models.tv_details_content_ratings import TvDetailsContentRatings


class TestTvDetailsContentRatings(unittest.TestCase):
    """TvDetailsContentRatings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TvDetailsContentRatings:
        """Test TvDetailsContentRatings
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TvDetailsContentRatings`
        """
        model = TvDetailsContentRatings()
        if include_optional:
            return TvDetailsContentRatings(
                results = [
                    schemas.overseerr.models.tv_details_content_ratings_results_inner.TvDetails_contentRatings_results_inner(
                        iso_3166_1 = 'US',
                        rating = 'TV-14', )
                    ]
            )
        else:
            return TvDetailsContentRatings(
        )
        """

    def testTvDetailsContentRatings(self):
        """Test TvDetailsContentRatings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
