# coding: utf-8

"""
Overseerr API

This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.overseerr.models.user_user_id_settings_password_get200_response import (
    UserUserIdSettingsPasswordGet200Response,
)


class TestUserUserIdSettingsPasswordGet200Response(unittest.TestCase):
    """UserUserIdSettingsPasswordGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> UserUserIdSettingsPasswordGet200Response:
        """Test UserUserIdSettingsPasswordGet200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserUserIdSettingsPasswordGet200Response`
        """
        model = UserUserIdSettingsPasswordGet200Response()
        if include_optional:
            return UserUserIdSettingsPasswordGet200Response(
                has_password = True
            )
        else:
            return UserUserIdSettingsPasswordGet200Response(
        )
        """

    def testUserUserIdSettingsPasswordGet200Response(self):
        """Test UserUserIdSettingsPasswordGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
