# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_search_results200_response_search_inner import (
    GetSearchResults200ResponseSearchInner,
)


class TestGetSearchResults200ResponseSearchInner(unittest.TestCase):
    """GetSearchResults200ResponseSearchInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSearchResults200ResponseSearchInner:
        """Test GetSearchResults200ResponseSearchInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetSearchResults200ResponseSearchInner`
        """
        model = GetSearchResults200ResponseSearchInner()
        if include_optional:
            return GetSearchResults200ResponseSearchInner(
                title = '',
                year = 1.337,
                score = 1.337,
                score_average = 1.337,
                type = '',
                ids = openapi_client.models.get_search_results_200_response_search_inner_ids.Get_Search_Results_200_response_search_inner_ids(
                    imdbid = '',
                    tmdbid = 1.337,
                    traktid = 1.337,
                    malid = null,
                    tvdbid = null, )
            )
        else:
            return GetSearchResults200ResponseSearchInner(
                title = '',
                year = 1.337,
                score = 1.337,
                score_average = 1.337,
                type = '',
                ids = openapi_client.models.get_search_results_200_response_search_inner_ids.Get_Search_Results_200_response_search_inner_ids(
                    imdbid = '',
                    tmdbid = 1.337,
                    traktid = 1.337,
                    malid = null,
                    tvdbid = null, ),
        )
        """

    def testGetSearchResults200ResponseSearchInner(self):
        """Test GetSearchResults200ResponseSearchInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
