# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.retrieve_collection200_response_pagination import (
    RetrieveCollection200ResponsePagination,
)


class TestRetrieveCollection200ResponsePagination(unittest.TestCase):
    """RetrieveCollection200ResponsePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> RetrieveCollection200ResponsePagination:
        """Test RetrieveCollection200ResponsePagination
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RetrieveCollection200ResponsePagination`
        """
        model = RetrieveCollection200ResponsePagination()
        if include_optional:
            return RetrieveCollection200ResponsePagination(
                page = 1.337,
                limit = 1.337,
                total_movies = 1.337,
                total_shows = 1.337,
                has_more = True
            )
        else:
            return RetrieveCollection200ResponsePagination(
        )
        """

    def testRetrieveCollection200ResponsePagination(self):
        """Test RetrieveCollection200ResponsePagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
