# coding: utf-8

"""
listrr.pro V1

An extensive API for working with listrr.pro

The version of the OpenAPI document: v1
Contact: developers@listrr.pro
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.listrr.models.listrr_contracts_models_api_paged_response1_listrr_contracts_models_api_movie_dto import (
    ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto,
)


class TestListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto(
    unittest.TestCase
):
    """ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto:
        """Test ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto`
        """
        model = ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto()
        if include_optional:
            return ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto(
                items = [
                    schemas.listrr.models.listrr/contracts/models/api/movie_dto.listrr.Contracts.Models.API.MovieDto(
                        id = '',
                        name = '',
                        release_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        im_db_id = '',
                        tm_db_id = 56, )
                    ],
                count = 56,
                pages = 56
            )
        else:
            return ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto(
        )
        """

    def testListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto(
        self,
    ):
        """Test ListrrContractsModelsAPIPagedResponse1ListrrContractsModelsAPIMovieDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
