# coding: utf-8

"""
listrr.pro V1

An extensive API for working with listrr.pro

The version of the OpenAPI document: v1
Contact: developers@listrr.pro
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.listrr.models.listrr_contracts_enum_sort_by_direction_enum import (
    ListrrContractsEnumSortByDirectionEnum,
)


class TestListrrContractsEnumSortByDirectionEnum(unittest.TestCase):
    """ListrrContractsEnumSortByDirectionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListrrContractsEnumSortByDirectionEnum(self):
        """Test ListrrContractsEnumSortByDirectionEnum"""
        # inst = ListrrContractsEnumSortByDirectionEnum()


if __name__ == "__main__":
    unittest.main()
