# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/Jackett/Jackett/refs/heads/master/src/Jackett.Common/Definitions/schema.json
#   timestamp: 2025-12-08T11:17:22+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, constr


class Language(StrEnum):
    af = 'af'
    af_ZA = 'af-ZA'
    ar = 'ar'
    ar_AE = 'ar-AE'
    ar_BH = 'ar-BH'
    ar_DZ = 'ar-DZ'
    ar_EG = 'ar-EG'
    ar_IQ = 'ar-IQ'
    ar_JO = 'ar-JO'
    ar_KW = 'ar-KW'
    ar_LB = 'ar-LB'
    ar_LY = 'ar-LY'
    ar_MA = 'ar-MA'
    ar_OM = 'ar-OM'
    ar_QA = 'ar-QA'
    ar_SA = 'ar-SA'
    ar_SY = 'ar-SY'
    ar_TN = 'ar-TN'
    ar_YE = 'ar-YE'
    az = 'az'
    az_AZ = 'az-AZ'
    be = 'be'
    be_BY = 'be-BY'
    bg = 'bg'
    bg_BG = 'bg-BG'
    bs_BA = 'bs-BA'
    ca = 'ca'
    ca_ES = 'ca-ES'
    cs = 'cs'
    cs_CZ = 'cs-CZ'
    cy = 'cy'
    cy_GB = 'cy-GB'
    da = 'da'
    da_DK = 'da-DK'
    de = 'de'
    de_AT = 'de-AT'
    de_CH = 'de-CH'
    de_DE = 'de-DE'
    de_LI = 'de-LI'
    de_LU = 'de-LU'
    dv = 'dv'
    dv_MV = 'dv-MV'
    el = 'el'
    el_GR = 'el-GR'
    en = 'en'
    en_AU = 'en-AU'
    en_BZ = 'en-BZ'
    en_CA = 'en-CA'
    en_CB = 'en-CB'
    en_GB = 'en-GB'
    en_IE = 'en-IE'
    en_JM = 'en-JM'
    en_NZ = 'en-NZ'
    en_PH = 'en-PH'
    en_TT = 'en-TT'
    en_US = 'en-US'
    en_ZA = 'en-ZA'
    en_ZW = 'en-ZW'
    eo = 'eo'
    es = 'es'
    es_AR = 'es-AR'
    es_BO = 'es-BO'
    es_CL = 'es-CL'
    es_CO = 'es-CO'
    es_CR = 'es-CR'
    es_DO = 'es-DO'
    es_EC = 'es-EC'
    es_ES = 'es-ES'
    es_GT = 'es-GT'
    es_HN = 'es-HN'
    es_MX = 'es-MX'
    es_NI = 'es-NI'
    es_PA = 'es-PA'
    es_PE = 'es-PE'
    es_PR = 'es-PR'
    es_PY = 'es-PY'
    es_SV = 'es-SV'
    es_UY = 'es-UY'
    es_VE = 'es-VE'
    et = 'et'
    et_EE = 'et-EE'
    eu = 'eu'
    eu_ES = 'eu-ES'
    fa = 'fa'
    fa_IR = 'fa-IR'
    fi = 'fi'
    fi_FI = 'fi-FI'
    fo = 'fo'
    fo_FO = 'fo-FO'
    fr = 'fr'
    fr_BE = 'fr-BE'
    fr_CA = 'fr-CA'
    fr_CH = 'fr-CH'
    fr_FR = 'fr-FR'
    fr_LU = 'fr-LU'
    fr_MC = 'fr-MC'
    gl = 'gl'
    gl_ES = 'gl-ES'
    gu = 'gu'
    gu_IN = 'gu-IN'
    he = 'he'
    he_IL = 'he-IL'
    hi = 'hi'
    hi_IN = 'hi-IN'
    hr = 'hr'
    hr_BA = 'hr-BA'
    hr_HR = 'hr-HR'
    hu = 'hu'
    hu_HU = 'hu-HU'
    hy = 'hy'
    hy_AM = 'hy-AM'
    id = 'id'
    id_ID = 'id-ID'
    is_ = 'is'
    is_IS = 'is-IS'
    it = 'it'
    it_CH = 'it-CH'
    it_IT = 'it-IT'
    ja = 'ja'
    ja_JP = 'ja-JP'
    ka = 'ka'
    ka_GE = 'ka-GE'
    kk = 'kk'
    kk_KZ = 'kk-KZ'
    kn = 'kn'
    kn_IN = 'kn-IN'
    ko = 'ko'
    ko_KR = 'ko-KR'
    kok = 'kok'
    kok_IN = 'kok-IN'
    ky = 'ky'
    ky_KG = 'ky-KG'
    lt = 'lt'
    lt_LT = 'lt-LT'
    lv = 'lv'
    lv_LV = 'lv-LV'
    mi = 'mi'
    mi_NZ = 'mi-NZ'
    mk = 'mk'
    mk_MK = 'mk-MK'
    mn = 'mn'
    mn_MN = 'mn-MN'
    mr = 'mr'
    mr_IN = 'mr-IN'
    ms = 'ms'
    ms_BN = 'ms-BN'
    ms_MY = 'ms-MY'
    mt = 'mt'
    mt_MT = 'mt-MT'
    nb = 'nb'
    nb_NO = 'nb-NO'
    nl = 'nl'
    nl_BE = 'nl-BE'
    nl_NL = 'nl-NL'
    nn_NO = 'nn-NO'
    ns = 'ns'
    ns_ZA = 'ns-ZA'
    pa = 'pa'
    pa_IN = 'pa-IN'
    pl = 'pl'
    pl_PL = 'pl-PL'
    ps = 'ps'
    ps_AR = 'ps-AR'
    pt = 'pt'
    pt_BR = 'pt-BR'
    pt_PT = 'pt-PT'
    qu = 'qu'
    qu_BO = 'qu-BO'
    qu_EC = 'qu-EC'
    qu_PE = 'qu-PE'
    ro = 'ro'
    ro_RO = 'ro-RO'
    ru = 'ru'
    ru_RU = 'ru-RU'
    sa = 'sa'
    sa_IN = 'sa-IN'
    se = 'se'
    se_FI = 'se-FI'
    se_NO = 'se-NO'
    se_SE = 'se-SE'
    sk = 'sk'
    sk_SK = 'sk-SK'
    sl = 'sl'
    sl_SI = 'sl-SI'
    sq = 'sq'
    sq_AL = 'sq-AL'
    sr_BA = 'sr-BA'
    sr_SP = 'sr-SP'
    sv = 'sv'
    sv_FI = 'sv-FI'
    sv_SE = 'sv-SE'
    sw = 'sw'
    sw_KE = 'sw-KE'
    syr = 'syr'
    syr_SY = 'syr-SY'
    ta = 'ta'
    ta_IN = 'ta-IN'
    te = 'te'
    te_IN = 'te-IN'
    th = 'th'
    th_TH = 'th-TH'
    tl = 'tl'
    tl_PH = 'tl-PH'
    tn = 'tn'
    tn_ZA = 'tn-ZA'
    tr = 'tr'
    tr_TR = 'tr-TR'
    tt = 'tt'
    tt_RU = 'tt-RU'
    ts = 'ts'
    uk = 'uk'
    uk_UA = 'uk-UA'
    ur = 'ur'
    ur_PK = 'ur-PK'
    uz = 'uz'
    uz_UZ = 'uz-UZ'
    vi = 'vi'
    vi_VN = 'vi-VN'
    xh = 'xh'
    xh_ZA = 'xh-ZA'
    zh = 'zh'
    zh_CN = 'zh-CN'
    zh_HK = 'zh-HK'
    zh_MO = 'zh-MO'
    zh_SG = 'zh-SG'
    zh_TW = 'zh-TW'
    zu = 'zu'
    zu_ZA = 'zu-ZA'


class Type(StrEnum):
    public = 'public'
    semi_private = 'semi-private'
    private = 'private'


class SearchEnum(StrEnum):
    q = 'q'


class TvSearchEnum(StrEnum):
    q = 'q'
    season = 'season'
    ep = 'ep'
    imdbid = 'imdbid'
    tvdbid = 'tvdbid'
    tmdbid = 'tmdbid'
    tvmazeid = 'tvmazeid'
    traktid = 'traktid'
    doubanid = 'doubanid'
    year = 'year'
    genre = 'genre'


class MovieSearchEnum(StrEnum):
    q = 'q'
    imdbid = 'imdbid'
    tmdbid = 'tmdbid'
    traktid = 'traktid'
    doubanid = 'doubanid'
    year = 'year'
    genre = 'genre'


class MusicSearchEnum(StrEnum):
    q = 'q'
    album = 'album'
    artist = 'artist'
    label = 'label'
    track = 'track'
    year = 'year'
    genre = 'genre'


class BookSearchEnum(StrEnum):
    q = 'q'
    title = 'title'
    author = 'author'
    publisher = 'publisher'
    year = 'year'
    genre = 'genre'


class Modes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    search: list[SearchEnum]
    tv_search: list[TvSearchEnum] | None = Field(None, alias='tv-search')
    movie_search: list[MovieSearchEnum] | None = Field(None, alias='movie-search')
    music_search: list[MusicSearchEnum] | None = Field(None, alias='music-search')
    book_search: list[BookSearchEnum] | None = Field(None, alias='book-search')


class Type1(StrEnum):
    info = 'info'
    text = 'text'
    password = 'password'
    checkbox = 'checkbox'
    select = 'select'
    info_category_8000 = 'info_category_8000'
    info_cookie = 'info_cookie'
    info_flaresolverr = 'info_flaresolverr'
    info_useragent = 'info_useragent'


class SettingsField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    label: str | None = None
    type: Type1
    default: str | int | bool | None = None
    options: dict[constr(pattern=r'^.*$'), str] | None = None
    defaults: list[str] | None = None


class Method(StrEnum):
    form = 'form'
    post = 'post'
    cookie = 'cookie'
    get = 'get'
    oneurl = 'oneurl'


class PageTestBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    selector: str


class Type2(StrEnum):
    image = 'image'
    text = 'text'


class CaptchaBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type2
    selector: str
    input: str


class Type3(StrEnum):
    json = 'json'
    xml = 'xml'


class ResponseBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type3
    noResultsMessage: str | None = None


class Name(StrEnum):
    andmatch = 'andmatch'
    strdump = 'strdump'


class RowFilterBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name
    args: list[str | float | bool] | str | int | None = None


class Name1(StrEnum):
    querystring = 'querystring'
    timeparse = 'timeparse'
    dateparse = 'dateparse'
    regexp = 'regexp'
    re_replace = 're_replace'
    split = 'split'
    replace = 'replace'
    trim = 'trim'
    prepend = 'prepend'
    append = 'append'
    tolower = 'tolower'
    toupper = 'toupper'
    urldecode = 'urldecode'
    urlencode = 'urlencode'
    htmldecode = 'htmldecode'
    htmlencode = 'htmlencode'
    timeago = 'timeago'
    reltime = 'reltime'
    fuzzytime = 'fuzzytime'
    validfilename = 'validfilename'
    diacritics = 'diacritics'
    jsonjoinarray = 'jsonjoinarray'
    hexdump = 'hexdump'
    strdump = 'strdump'
    validate = 'validate'


class FilterBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name1
    args: list[str | float | bool] | str | int | None = None


class IndexerCategories(StrEnum):
    Console = 'Console'
    Console_NDS = 'Console/NDS'
    Console_PSP = 'Console/PSP'
    Console_Wii = 'Console/Wii'
    Console_XBox = 'Console/XBox'
    Console_XBox_360 = 'Console/XBox 360'
    Console_Wiiware = 'Console/Wiiware'
    Console_XBox_360_DLC = 'Console/XBox 360 DLC'
    Console_PS3 = 'Console/PS3'
    Console_Other = 'Console/Other'
    Console_3DS = 'Console/3DS'
    Console_PS_Vita = 'Console/PS Vita'
    Console_WiiU = 'Console/WiiU'
    Console_XBox_One = 'Console/XBox One'
    Console_PS4 = 'Console/PS4'
    Movies = 'Movies'
    Movies_Foreign = 'Movies/Foreign'
    Movies_Other = 'Movies/Other'
    Movies_SD = 'Movies/SD'
    Movies_HD = 'Movies/HD'
    Movies_UHD = 'Movies/UHD'
    Movies_BluRay = 'Movies/BluRay'
    Movies_3D = 'Movies/3D'
    Movies_DVD = 'Movies/DVD'
    Movies_WEB_DL = 'Movies/WEB-DL'
    Audio = 'Audio'
    Audio_MP3 = 'Audio/MP3'
    Audio_Video = 'Audio/Video'
    Audio_Audiobook = 'Audio/Audiobook'
    Audio_Lossless = 'Audio/Lossless'
    Audio_Other = 'Audio/Other'
    Audio_Foreign = 'Audio/Foreign'
    PC = 'PC'
    PC_0day = 'PC/0day'
    PC_ISO = 'PC/ISO'
    PC_Mac = 'PC/Mac'
    PC_Mobile_Other = 'PC/Mobile-Other'
    PC_Games = 'PC/Games'
    PC_Mobile_iOS = 'PC/Mobile-iOS'
    PC_Mobile_Android = 'PC/Mobile-Android'
    TV = 'TV'
    TV_WEB_DL = 'TV/WEB-DL'
    TV_Foreign = 'TV/Foreign'
    TV_SD = 'TV/SD'
    TV_HD = 'TV/HD'
    TV_UHD = 'TV/UHD'
    TV_Other = 'TV/Other'
    TV_Sport = 'TV/Sport'
    TV_Anime = 'TV/Anime'
    TV_Documentary = 'TV/Documentary'
    XXX = 'XXX'
    XXX_DVD = 'XXX/DVD'
    XXX_WMV = 'XXX/WMV'
    XXX_XviD = 'XXX/XviD'
    XXX_x264 = 'XXX/x264'
    XXX_UHD = 'XXX/UHD'
    XXX_Pack = 'XXX/Pack'
    XXX_ImageSet = 'XXX/ImageSet'
    XXX_Other = 'XXX/Other'
    XXX_SD = 'XXX/SD'
    XXX_WEB_DL = 'XXX/WEB-DL'
    Books = 'Books'
    Books_Mags = 'Books/Mags'
    Books_EBook = 'Books/EBook'
    Books_Comics = 'Books/Comics'
    Books_Technical = 'Books/Technical'
    Books_Other = 'Books/Other'
    Books_Foreign = 'Books/Foreign'
    Other = 'Other'
    Other_Misc = 'Other/Misc'
    Other_Hashed = 'Other/Hashed'


class CategoryMapping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int | str
    cat: IndexerCategories
    desc: str | None = None
    default: bool | None = None


class SelectorBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: str | None = None
    attribute: str | None = None
    optional: bool | None = None
    default: str | float | None = None
    case: dict[constr(pattern=r'^.*$'), str | float] | None = None
    remove: str | None = None
    text: str | float | None = None
    filters: list[FilterBlock] | None = None


class SearchPathBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    method: str | None = None
    followredirect: bool | None = None
    categories: list[int | str] | None = None
    inputs: (
        dict[constr(pattern=r'^((\$raw)|[A-Za-z0-9.\-_[\]]*)$'), int | str] | None
    ) = None
    inheritinputs: bool | None = None
    queryseparator: str | None = None
    response: ResponseBlock | None = None


class RowsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    after: int | None = None
    dateheaders: SelectorBlock | None = None
    selector: str | None = None
    attribute: str | None = None
    optional: bool | None = None
    multiple: bool | None = None
    missingAttributeEqualsNoResults: bool | None = None
    case: dict[constr(pattern=r'^[A-Za-z0-9]*$'), str] | None = None
    remove: str | None = None
    text: str | float | None = None
    filters: list[RowFilterBlock] | None = None
    count: SelectorBlock | None = None


class FieldsBlock(
    RootModel[
        dict[constr(pattern=r'^_[A-Za-z0-9-_]*$'), SelectorBlock]
        | dict[constr(pattern=r'^((title|description)\|(append))?$'), SelectorBlock]
        | dict[
            constr(pattern=r'^((category|categorydesc)\|(noappend|append))?$'),
            SelectorBlock,
        ]
        | dict[
            constr(
                pattern=r'^(download|magnet|infohash|details|comments|title|description|category|categorydesc|size|leechers|seeders|date|files|grabs|downloadvolumefactor|uploadvolumefactor|minimumratio|minimumseedtime|imdb|imdbid|tmdbid|rageid|tvdbid|tvmazeid|traktid|doubanid|poster|genre|year|author|booktitle|publisher|album|artist|label|track)(_([A-Za-z0-9_])*)?$'
            ),
            SelectorBlock,
        ]
    ]
):
    root: (
        dict[constr(pattern=r'^_[A-Za-z0-9-_]*$'), SelectorBlock]
        | dict[constr(pattern=r'^((title|description)\|(append))?$'), SelectorBlock]
        | dict[
            constr(pattern=r'^((category|categorydesc)\|(noappend|append))?$'),
            SelectorBlock,
        ]
        | dict[
            constr(
                pattern=r'^(download|magnet|infohash|details|comments|title|description|category|categorydesc|size|leechers|seeders|date|files|grabs|downloadvolumefactor|uploadvolumefactor|minimumratio|minimumseedtime|imdb|imdbid|tmdbid|rageid|tvdbid|tvmazeid|traktid|doubanid|poster|genre|year|author|booktitle|publisher|album|artist|label|track)(_([A-Za-z0-9_])*)?$'
            ),
            SelectorBlock,
        ]
    ) = Field(..., title='FieldsBlock')


class SelectorField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: str | None = None
    attribute: str | None = None
    usebeforeresponse: bool | None = None
    filters: list[FilterBlock] | None = None


class Caps1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    categories: dict[constr(pattern=r'^.*$'), IndexerCategories]
    categorymappings: list[CategoryMapping] | None = None
    modes: Modes
    allowrawsearch: bool | None = None


class Caps2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    categories: dict[constr(pattern=r'^.*$'), IndexerCategories] | None = None
    categorymappings: list[CategoryMapping]
    modes: Modes
    allowrawsearch: bool | None = None


class Caps(RootModel[Caps1 | Caps2]):
    root: Caps1 | Caps2 = Field(..., title='Caps')


class ErrorBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str | None = None
    selector: str
    message: SelectorBlock | None = None


class Search1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str | None = None
    paths: list[SearchPathBlock]
    allowEmptyInputs: bool | None = None
    inputs: (
        dict[constr(pattern=r'^((\$raw)|[A-Za-z0-9.\-_[\]]*)$'), float | str | bool]
        | None
    ) = None
    headers: dict[constr(pattern=r'^[A-Za-z0-9-]*$'), list[str]] | None = None
    keywordsfilters: list[FilterBlock] | None = None
    error: list[ErrorBlock] | None = None
    preprocessingfilters: list[FilterBlock] | None = None
    rows: RowsBlock
    fields: FieldsBlock


class Search2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    paths: list[SearchPathBlock] | None = None
    allowEmptyInputs: bool | None = None
    inputs: (
        dict[constr(pattern=r'^((\$raw)|[A-Za-z0-9.\-_[\]]*)$'), float | str | bool]
        | None
    ) = None
    headers: dict[constr(pattern=r'^[A-Za-z0-9-]*$'), list[str]] | None = None
    keywordsfilters: list[FilterBlock] | None = None
    error: list[ErrorBlock] | None = None
    preprocessingfilters: list[FilterBlock] | None = None
    rows: RowsBlock
    fields: FieldsBlock


class Search(RootModel[Search1 | Search2]):
    root: Search1 | Search2 = Field(..., title='Search')


class BeforeBlock1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    pathselector: SelectorField | None = None
    method: str | None = None
    inputs: dict[constr(pattern=r'^[A-Za-z0-9_]*$'), int | str] | None = None
    queryseparator: str | None = None


class BeforeBlock2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str | None = None
    pathselector: SelectorField
    method: str | None = None
    inputs: dict[constr(pattern=r'^[A-Za-z0-9_]*$'), int | str] | None = None
    queryseparator: str | None = None


class BeforeBlock(RootModel[BeforeBlock1 | BeforeBlock2]):
    root: BeforeBlock1 | BeforeBlock2 = Field(..., title='BeforeBlock')


class InfoHashBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hash: SelectorField | None = None
    title: SelectorField | None = None
    usebeforeresponse: bool | None = None


class Login(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: Method | None = None
    cookies: list[str] | None = None
    path: str | None = None
    submitpath: str | None = None
    form: str | None = None
    captcha: CaptchaBlock | None = None
    inputs: dict[constr(pattern=r'^.*$'), float | str | bool] | None = None
    selectors: bool | None = None
    selectorinputs: dict[constr(pattern=r'^[A-Za-z0-9_]*$'), SelectorBlock] | None = (
        None
    )
    getselectorinputs: (
        dict[constr(pattern=r'^[A-Za-z0-9_]*$'), SelectorBlock] | None
    ) = None
    error: list[ErrorBlock] | None = None
    test: PageTestBlock | None = None
    headers: dict[constr(pattern=r'^[A-Za-z0-9-]*$'), list[str]] | None = None


class DownloadBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: str | None = None
    before: BeforeBlock | None = None
    selectors: list[Any] | None = None
    infohash: InfoHashBlock | None = None
    headers: dict[constr(pattern=r'^[A-Za-z0-9-]*$'), list[str]] | None = None


class SchemaRoot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    replaces: list[str] | None = None
    name: str
    description: str
    language: Language
    type: Type
    encoding: str
    followredirect: bool | None = None
    testlinktorrent: bool | None = None
    requestDelay: float | None = None
    links: list[AnyUrl]
    legacylinks: list[AnyUrl] | None = None
    certificates: list[str] | None = None
    caps: Caps
    settings: list[SettingsField] | None = None
    login: Login | None = None
    search: Search
    download: DownloadBlock | None = None


class Model(RootModel[SchemaRoot]):
    root: SchemaRoot
