# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self


class GetListItems200ResponseMoviesInner(BaseModel):
    """
    GetListItems200ResponseMoviesInner
    """  # noqa: E501

    id: Union[StrictFloat, StrictInt]
    rank: Union[StrictFloat, StrictInt]
    adult: Union[StrictFloat, StrictInt]
    title: StrictStr
    imdb_id: StrictStr
    tvdb_id: Optional[Any]
    language: StrictStr
    mediatype: StrictStr
    release_year: Union[StrictFloat, StrictInt]
    spoken_language: StrictStr
    __properties: ClassVar[List[str]] = [
        "id",
        "rank",
        "adult",
        "title",
        "imdb_id",
        "tvdb_id",
        "language",
        "mediatype",
        "release_year",
        "spoken_language",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetListItems200ResponseMoviesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tvdb_id (nullable) is None
        # and model_fields_set contains the field
        if self.tvdb_id is None and "tvdb_id" in self.model_fields_set:
            _dict["tvdb_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetListItems200ResponseMoviesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "rank": obj.get("rank"),
                "adult": obj.get("adult"),
                "title": obj.get("title"),
                "imdb_id": obj.get("imdb_id"),
                "tvdb_id": obj.get("tvdb_id"),
                "language": obj.get("language"),
                "mediatype": obj.get("mediatype"),
                "release_year": obj.get("release_year"),
                "spoken_language": obj.get("spoken_language"),
            }
        )
        return _obj
