# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from schemas.mdblist.models.retrieve_collection200_response_shows_inner_show import (
    RetrieveCollection200ResponseShowsInnerShow,
)
from typing import Optional, Set
from typing_extensions import Self


class RetrieveCollection200ResponseShowsInner(BaseModel):
    """
    RetrieveCollection200ResponseShowsInner
    """  # noqa: E501

    collected_at: Optional[StrictStr] = None
    show: Optional[RetrieveCollection200ResponseShowsInnerShow] = None
    __properties: ClassVar[List[str]] = ["collected_at", "show"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrieveCollection200ResponseShowsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of show
        if self.show:
            _dict["show"] = self.show.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrieveCollection200ResponseShowsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "collected_at": obj.get("collected_at"),
                "show": (
                    RetrieveCollection200ResponseShowsInnerShow.from_dict(obj["show"])
                    if obj.get("show") is not None
                    else None
                ),
            }
        )
        return _obj
