"""Add new anime related columns

Revision ID: ce6e2f0f12e1
Revises: d6c06f357feb
Create Date: 2025-02-25 17:58:57.047869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6e2f0f12e1'
down_revision: Union[str, None] = 'd6c06f357feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MediaItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trakt_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('anilist_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mal_id', sa.String(), nullable=True))

    with op.batch_alter_table('Season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_episode_mapping', sa.JSON(), nullable=True))

    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_season_mapping', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_column('alt_season_mapping')

    with op.batch_alter_table('Season', schema=None) as batch_op:
        batch_op.drop_column('alt_episode_mapping')

    with op.batch_alter_table('MediaItem', schema=None) as batch_op:
        batch_op.drop_column('mal_id')
        batch_op.drop_column('anilist_id')
        batch_op.drop_column('trakt_id')

    # ### end Alembic commands ###
