from datetime import datetime
from typing import Any, Protocol

from program.queue.models import (
    ContentQueueEntry,
    EnqueueResult,
    PipelineStage,
    QueueEntry,
    QueueStats,
)


class PipelineQueueReader(Protocol):
    def get(self, item_id: int) -> QueueEntry | None: ...

    def contains_item(self, item_id: int) -> bool: ...

    def contains_content(self, content_item: Any) -> bool: ...

    def count_by_stage(self) -> dict[PipelineStage, int]: ...

    def stats(self, now: datetime) -> QueueStats: ...

    def peek_ordered(
        self, stage: PipelineStage, now: datetime, limit: int
    ) -> list[QueueEntry]: ...

    def peek_due(
        self, stage: PipelineStage, now: datetime, limit: int
    ) -> list[QueueEntry]: ...

    def pop_due(self, stage: PipelineStage, now: datetime) -> QueueEntry | None: ...

    def content_entries(self) -> list[ContentQueueEntry]: ...

    def all_item_entries(self) -> list[QueueEntry]: ...

    def item_ids_in_stage(self, stage: PipelineStage) -> set[int]: ...


class PipelineQueueMutator(Protocol):
    def enqueue(self, entry: QueueEntry) -> EnqueueResult: ...

    def enqueue_content(self, entry: ContentQueueEntry) -> EnqueueResult: ...

    def enqueue_many(self, entries: list[QueueEntry]) -> int: ...

    def dequeue(self, item_id: int) -> bool: ...

    def dequeue_content(self, content_item: Any) -> bool: ...

    def update_run_at(self, item_id: int, run_at: datetime) -> bool: ...

    def update_state(self, item_id: int, state: Any) -> bool: ...

    def merge_item(
        self,
        item_id: int,
        *,
        run_at: datetime | None = None,
        item_state: Any | None = None,
    ) -> bool: ...

    def normalize_run_at(self) -> None: ...

    def clear(self) -> None: ...
