# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.trending_tv200_response import TrendingTv200Response


class TestTrendingTv200Response(unittest.TestCase):
    """TrendingTv200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendingTv200Response:
        """Test TrendingTv200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TrendingTv200Response`
        """
        model = TrendingTv200Response()
        if include_optional:
            return TrendingTv200Response(
                page = 1,
                results = [
                    schemas.tmdb.models.trending_tv_200_response_results_inner.trending_tv_200_response_results_inner(
                        adult = False,
                        backdrop_path = '/8P15FsYcTwQZ4G5rRMd1TKD14Aq.jpg',
                        id = 103768,
                        name = 'Sweet Tooth',
                        original_language = 'en',
                        original_name = 'Sweet Tooth',
                        overview = 'On a perilous adventure across a post-apocalyptic world, a lovable boy who's half-human and half-deer searches for a new beginning with a gruff protector.',
                        poster_path = '/dBxxtfhC4vYrxB2fLsSxOTY2dQc.jpg',
                        media_type = 'tv',
                        genre_ids = [
                            18
                            ],
                        popularity = 137.498,
                        first_air_date = '2021-06-04',
                        vote_average = 7.928,
                        vote_count = 1094,
                        origin_country = [
                            'US'
                            ], )
                    ],
                total_pages = 1000,
                total_results = 20000
            )
        else:
            return TrendingTv200Response(
        )
        """

    def testTrendingTv200Response(self):
        """Test TrendingTv200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
