# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.tv_series_aggregate_credits200_response_crew_inner_jobs_inner import (
    TvSeriesAggregateCredits200ResponseCrewInnerJobsInner,
)


class TestTvSeriesAggregateCredits200ResponseCrewInnerJobsInner(unittest.TestCase):
    """TvSeriesAggregateCredits200ResponseCrewInnerJobsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TvSeriesAggregateCredits200ResponseCrewInnerJobsInner:
        """Test TvSeriesAggregateCredits200ResponseCrewInnerJobsInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TvSeriesAggregateCredits200ResponseCrewInnerJobsInner`
        """
        model = TvSeriesAggregateCredits200ResponseCrewInnerJobsInner()
        if include_optional:
            return TvSeriesAggregateCredits200ResponseCrewInnerJobsInner(
                credit_id = '54eee9e5c3a3686d5800584e',
                job = 'Production Design',
                episode_count = 43
            )
        else:
            return TvSeriesAggregateCredits200ResponseCrewInnerJobsInner(
        )
        """

    def testTvSeriesAggregateCredits200ResponseCrewInnerJobsInner(self):
        """Test TvSeriesAggregateCredits200ResponseCrewInnerJobsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
