# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.credit_details200_response_person import (
    CreditDetails200ResponsePerson,
)


class TestCreditDetails200ResponsePerson(unittest.TestCase):
    """CreditDetails200ResponsePerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditDetails200ResponsePerson:
        """Test CreditDetails200ResponsePerson
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreditDetails200ResponsePerson`
        """
        model = CreditDetails200ResponsePerson()
        if include_optional:
            return CreditDetails200ResponsePerson(
                adult = False,
                id = 1253360,
                name = 'Pedro Pascal',
                original_name = 'Pedro Pascal',
                media_type = 'person',
                popularity = 106.095,
                gender = 2,
                known_for_department = 'Acting',
                profile_path = '/dBOrm29cr7NUrjiDQMTtrTyDpfy.jpg'
            )
        else:
            return CreditDetails200ResponsePerson(
        )
        """

    def testCreditDetails200ResponsePerson(self):
        """Test CreditDetails200ResponsePerson"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
