# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.tv_season_translations200_response_translations_inner_data import (
    TvSeasonTranslations200ResponseTranslationsInnerData,
)


class TestTvSeasonTranslations200ResponseTranslationsInnerData(unittest.TestCase):
    """TvSeasonTranslations200ResponseTranslationsInnerData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TvSeasonTranslations200ResponseTranslationsInnerData:
        """Test TvSeasonTranslations200ResponseTranslationsInnerData
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TvSeasonTranslations200ResponseTranslationsInnerData`
        """
        model = TvSeasonTranslations200ResponseTranslationsInnerData()
        if include_optional:
            return TvSeasonTranslations200ResponseTranslationsInnerData(
                name = '',
                overview = 'سلسلة درامية مبنية على سلسلة روايات لـ جورج آر آر مارتن بعنوان "إيه سونغ أوف آيس أن فاير" والتي حققت مبيعات كبيرة وتتمحور حول الصراعات التي كانت تحدث في العصور الوسطى بين العائلات النبيلة للسيطرة على عرش وستيروس.'
            )
        else:
            return TvSeasonTranslations200ResponseTranslationsInnerData(
        )
        """

    def testTvSeasonTranslations200ResponseTranslationsInnerData(self):
        """Test TvSeasonTranslations200ResponseTranslationsInnerData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
