# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.configuration_countries200_response_inner import (
    ConfigurationCountries200ResponseInner,
)


class TestConfigurationCountries200ResponseInner(unittest.TestCase):
    """ConfigurationCountries200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigurationCountries200ResponseInner:
        """Test ConfigurationCountries200ResponseInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConfigurationCountries200ResponseInner`
        """
        model = ConfigurationCountries200ResponseInner()
        if include_optional:
            return ConfigurationCountries200ResponseInner(
                iso_3166_1 = 'AD',
                english_name = 'Andorra',
                native_name = 'Andorra'
            )
        else:
            return ConfigurationCountries200ResponseInner(
        )
        """

    def testConfigurationCountries200ResponseInner(self):
        """Test ConfigurationCountries200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
