# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.account_details200_response_avatar_gravatar import (
    AccountDetails200ResponseAvatarGravatar,
)


class TestAccountDetails200ResponseAvatarGravatar(unittest.TestCase):
    """AccountDetails200ResponseAvatarGravatar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> AccountDetails200ResponseAvatarGravatar:
        """Test AccountDetails200ResponseAvatarGravatar
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountDetails200ResponseAvatarGravatar`
        """
        model = AccountDetails200ResponseAvatarGravatar()
        if include_optional:
            return AccountDetails200ResponseAvatarGravatar(
                hash = 'c9e9fc152ee756a900db85757c29815d'
            )
        else:
            return AccountDetails200ResponseAvatarGravatar(
        )
        """

    def testAccountDetails200ResponseAvatarGravatar(self):
        """Test AccountDetails200ResponseAvatarGravatar"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
