# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.certifications_tv_list200_response_certifications_gb_inner import (
    CertificationsTvList200ResponseCertificationsGBInner,
)


class TestCertificationsTvList200ResponseCertificationsGBInner(unittest.TestCase):
    """CertificationsTvList200ResponseCertificationsGBInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CertificationsTvList200ResponseCertificationsGBInner:
        """Test CertificationsTvList200ResponseCertificationsGBInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CertificationsTvList200ResponseCertificationsGBInner`
        """
        model = CertificationsTvList200ResponseCertificationsGBInner()
        if include_optional:
            return CertificationsTvList200ResponseCertificationsGBInner(
                certification = 'U',
                meaning = 'The U symbol stands for Universal. A U film should be suitable for audiences aged four years and over.',
                order = 0
            )
        else:
            return CertificationsTvList200ResponseCertificationsGBInner(
        )
        """

    def testCertificationsTvList200ResponseCertificationsGBInner(self):
        """Test CertificationsTvList200ResponseCertificationsGBInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
