# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.tv_series_details200_response_seasons_inner import (
    TvSeriesDetails200ResponseSeasonsInner,
)


class TestTvSeriesDetails200ResponseSeasonsInner(unittest.TestCase):
    """TvSeriesDetails200ResponseSeasonsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TvSeriesDetails200ResponseSeasonsInner:
        """Test TvSeriesDetails200ResponseSeasonsInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TvSeriesDetails200ResponseSeasonsInner`
        """
        model = TvSeriesDetails200ResponseSeasonsInner()
        if include_optional:
            return TvSeriesDetails200ResponseSeasonsInner(
                air_date = '2010-12-05',
                episode_count = 272,
                id = 3627,
                name = 'Specials',
                overview = '',
                poster_path = '/kMTcwNRfFKCZ0O2OaBZS0nZ2AIe.jpg',
                season_number = 0,
                vote_average = 0
            )
        else:
            return TvSeriesDetails200ResponseSeasonsInner(
        )
        """

    def testTvSeriesDetails200ResponseSeasonsInner(self):
        """Test TvSeriesDetails200ResponseSeasonsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
