# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.genre_movie_list200_response import GenreMovieList200Response


class TestGenreMovieList200Response(unittest.TestCase):
    """GenreMovieList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenreMovieList200Response:
        """Test GenreMovieList200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GenreMovieList200Response`
        """
        model = GenreMovieList200Response()
        if include_optional:
            return GenreMovieList200Response(
                genres = [
                    schemas.tmdb.models.genre_movie_list_200_response_genres_inner.genre_movie_list_200_response_genres_inner(
                        id = 28,
                        name = 'Action', )
                    ]
            )
        else:
            return GenreMovieList200Response(
        )
        """

    def testGenreMovieList200Response(self):
        """Test GenreMovieList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
