# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.certification_movie_list200_response_certifications_pt_inner import (
    CertificationMovieList200ResponseCertificationsPTInner,
)


class TestCertificationMovieList200ResponseCertificationsPTInner(unittest.TestCase):
    """CertificationMovieList200ResponseCertificationsPTInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CertificationMovieList200ResponseCertificationsPTInner:
        """Test CertificationMovieList200ResponseCertificationsPTInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CertificationMovieList200ResponseCertificationsPTInner`
        """
        model = CertificationMovieList200ResponseCertificationsPTInner()
        if include_optional:
            return CertificationMovieList200ResponseCertificationsPTInner(
                certification = 'Públicos',
                meaning = 'For all the public (especially designed for children under 3 years of age).',
                order = 1
            )
        else:
            return CertificationMovieList200ResponseCertificationsPTInner(
        )
        """

    def testCertificationMovieList200ResponseCertificationsPTInner(self):
        """Test CertificationMovieList200ResponseCertificationsPTInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
