# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.certifications_tv_list200_response_certifications_id_inner import (
    CertificationsTvList200ResponseCertificationsIDInner,
)


class TestCertificationsTvList200ResponseCertificationsIDInner(unittest.TestCase):
    """CertificationsTvList200ResponseCertificationsIDInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CertificationsTvList200ResponseCertificationsIDInner:
        """Test CertificationsTvList200ResponseCertificationsIDInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CertificationsTvList200ResponseCertificationsIDInner`
        """
        model = CertificationsTvList200ResponseCertificationsIDInner()
        if include_optional:
            return CertificationsTvList200ResponseCertificationsIDInner(
                certification = 'SU',
                meaning = 'Suitable for general audiences over the age of 2 years.',
                order = 1
            )
        else:
            return CertificationsTvList200ResponseCertificationsIDInner(
        )
        """

    def testCertificationsTvList200ResponseCertificationsIDInner(self):
        """Test CertificationsTvList200ResponseCertificationsIDInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
