# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.movie_details200_response_production_countries_inner import (
    MovieDetails200ResponseProductionCountriesInner,
)


class TestMovieDetails200ResponseProductionCountriesInner(unittest.TestCase):
    """MovieDetails200ResponseProductionCountriesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> MovieDetails200ResponseProductionCountriesInner:
        """Test MovieDetails200ResponseProductionCountriesInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MovieDetails200ResponseProductionCountriesInner`
        """
        model = MovieDetails200ResponseProductionCountriesInner()
        if include_optional:
            return MovieDetails200ResponseProductionCountriesInner(
                iso_3166_1 = 'US',
                name = 'United States of America'
            )
        else:
            return MovieDetails200ResponseProductionCountriesInner(
        )
        """

    def testMovieDetails200ResponseProductionCountriesInner(self):
        """Test MovieDetails200ResponseProductionCountriesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
