# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.search_multi200_response import SearchMulti200Response


class TestSearchMulti200Response(unittest.TestCase):
    """SearchMulti200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchMulti200Response:
        """Test SearchMulti200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SearchMulti200Response`
        """
        model = SearchMulti200Response()
        if include_optional:
            return SearchMulti200Response(
                page = 1,
                results = [
                    schemas.tmdb.models.search_multi_200_response_results_inner.search_multi_200_response_results_inner(
                        adult = False,
                        backdrop_path = '/aDYSnJAK0BTVeE8osOy22Kz3SXY.jpg',
                        id = 11,
                        title = 'Star Wars',
                        original_language = 'en',
                        original_title = 'Star Wars',
                        overview = 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
                        poster_path = '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
                        media_type = 'movie',
                        genre_ids = [
                            12
                            ],
                        popularity = 78.047,
                        release_date = '1977-05-25',
                        video = False,
                        vote_average = 8.208,
                        vote_count = 18528, )
                    ],
                total_pages = 11,
                total_results = 201
            )
        else:
            return SearchMulti200Response(
        )
        """

    def testSearchMulti200Response(self):
        """Test SearchMulti200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
