# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.movie_images200_response_posters_inner import (
    MovieImages200ResponsePostersInner,
)


class TestMovieImages200ResponsePostersInner(unittest.TestCase):
    """MovieImages200ResponsePostersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MovieImages200ResponsePostersInner:
        """Test MovieImages200ResponsePostersInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MovieImages200ResponsePostersInner`
        """
        model = MovieImages200ResponsePostersInner()
        if include_optional:
            return MovieImages200ResponsePostersInner(
                aspect_ratio = 0.667,
                height = 900,
                iso_639_1 = 'pt',
                file_path = '/r3pPehX4ik8NLYPpbDRAh0YRtMb.jpg',
                vote_average = 5.258,
                vote_count = 6,
                width = 600
            )
        else:
            return MovieImages200ResponsePostersInner(
        )
        """

    def testMovieImages200ResponsePostersInner(self):
        """Test MovieImages200ResponsePostersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
