# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.certifications_tv_list200_response_certifications_th_inner import (
    CertificationsTvList200ResponseCertificationsTHInner,
)


class TestCertificationsTvList200ResponseCertificationsTHInner(unittest.TestCase):
    """CertificationsTvList200ResponseCertificationsTHInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CertificationsTvList200ResponseCertificationsTHInner:
        """Test CertificationsTvList200ResponseCertificationsTHInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CertificationsTvList200ResponseCertificationsTHInner`
        """
        model = CertificationsTvList200ResponseCertificationsTHInner()
        if include_optional:
            return CertificationsTvList200ResponseCertificationsTHInner(
                certification = 'ส',
                meaning = 'Sor - Educational movies which the public should be encouraged to see.',
                order = 1
            )
        else:
            return CertificationsTvList200ResponseCertificationsTHInner(
        )
        """

    def testCertificationsTvList200ResponseCertificationsTHInner(self):
        """Test CertificationsTvList200ResponseCertificationsTHInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
