# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.company_details200_response import CompanyDetails200Response


class TestCompanyDetails200Response(unittest.TestCase):
    """CompanyDetails200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyDetails200Response:
        """Test CompanyDetails200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CompanyDetails200Response`
        """
        model = CompanyDetails200Response()
        if include_optional:
            return CompanyDetails200Response(
                description = '',
                headquarters = 'San Francisco, California',
                homepage = 'https://www.lucasfilm.com',
                id = 1,
                logo_path = '/o86DbpburjxrqAzEDhXZcyE8pDb.png',
                name = 'Lucasfilm Ltd.',
                origin_country = 'US',
                parent_company = None
            )
        else:
            return CompanyDetails200Response(
        )
        """

    def testCompanyDetails200Response(self):
        """Test CompanyDetails200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
