# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.tv_series_changes200_response_changes_inner_items_inner_original_value import (
    TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue,
)


class TestTvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue(
    unittest.TestCase
):
    """TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue:
        """Test TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue`
        """
        model = TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue()
        if include_optional:
            return TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue(
                poster = schemas.tmdb.models.tv_series_changes_200_response_changes_inner_items_inner_original_value_poster.tv_series_changes_200_response_changes_inner_items_inner_original_value_poster(
                    file_path = '/ouudK6RCNnsbT1CSXrlATXQIQTG.jpg',
                    iso_639_1 = 'fr', )
            )
        else:
            return TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue(
        )
        """

    def testTvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue(self):
        """Test TvSeriesChanges200ResponseChangesInnerItemsInnerOriginalValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
