# coding: utf-8

"""
tmdb-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.tmdb.models.certification_movie_list200_response_certifications_nz_inner import (
    CertificationMovieList200ResponseCertificationsNZInner,
)


class TestCertificationMovieList200ResponseCertificationsNZInner(unittest.TestCase):
    """CertificationMovieList200ResponseCertificationsNZInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> CertificationMovieList200ResponseCertificationsNZInner:
        """Test CertificationMovieList200ResponseCertificationsNZInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CertificationMovieList200ResponseCertificationsNZInner`
        """
        model = CertificationMovieList200ResponseCertificationsNZInner()
        if include_optional:
            return CertificationMovieList200ResponseCertificationsNZInner(
                certification = 'G',
                meaning = 'Suitable for general audiences.',
                order = 1
            )
        else:
            return CertificationMovieList200ResponseCertificationsNZInner(
        )
        """

    def testCertificationMovieList200ResponseCertificationsNZInner(self):
        """Test CertificationMovieList200ResponseCertificationsNZInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
