# coding: utf-8

"""
Prowlarr

Prowlarr API docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BookSearchParam(str, Enum):
    """
    BookSearchParam
    """

    """
    allowed enum values
    """
    Q = "q"
    TITLE = "title"
    AUTHOR = "author"
    PUBLISHER = "publisher"
    GENRE = "genre"
    YEAR = "year"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BookSearchParam from a JSON string"""
        return cls(json.loads(json_str))
