# coding: utf-8

"""
TVDB API V4

Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes.

The version of the OpenAPI document: 4.7.10
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from schemas.tvdb.models.artwork_base_record import ArtworkBaseRecord
from schemas.tvdb.models.episode_base_record import EpisodeBaseRecord
from schemas.tvdb.models.season_type import SeasonType
from schemas.tvdb.models.tag_option import TagOption
from schemas.tvdb.models.trailer import Trailer
from schemas.tvdb.models.translation import Translation
from typing import Optional, Set
from typing_extensions import Self
from schemas.tvdb.models.companies import Companies


class SeasonExtendedRecord(BaseModel):
    """
    extended season record
    """  # noqa: E501

    artwork: Optional[List[ArtworkBaseRecord]] = None
    companies: Optional[Dict[str, Any]] = None
    episodes: Optional[List[EpisodeBaseRecord]] = None
    id: Optional[StrictInt] = None
    image: Optional[StrictStr] = None
    image_type: Optional[StrictInt] = Field(default=None, alias="imageType")
    last_updated: Optional[StrictStr] = Field(default=None, alias="lastUpdated")
    name: Optional[StrictStr] = None
    name_translations: Optional[List[StrictStr]] = Field(
        default=None, alias="nameTranslations"
    )
    number: Optional[StrictInt] = None
    overview_translations: Optional[List[StrictStr]] = Field(
        default=None, alias="overviewTranslations"
    )
    series_id: Optional[StrictInt] = Field(default=None, alias="seriesId")
    trailers: Optional[List[Trailer]] = None
    type: Optional[SeasonType] = None
    tag_options: Optional[List[TagOption]] = Field(default=None, alias="tagOptions")
    translations: Optional[List[Translation]] = None
    year: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "artwork",
        "companies",
        "episodes",
        "id",
        "image",
        "imageType",
        "lastUpdated",
        "name",
        "nameTranslations",
        "number",
        "overviewTranslations",
        "seriesId",
        "trailers",
        "type",
        "tagOptions",
        "translations",
        "year",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SeasonExtendedRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in artwork (list)
        _items = []
        if self.artwork:
            for _item_artwork in self.artwork:
                if _item_artwork:
                    _items.append(_item_artwork.to_dict())
            _dict["artwork"] = _items
        # override the default output from pydantic by calling `to_dict()` of companies
        if self.companies:
            _dict["companies"] = self.companies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in episodes (list)
        _items = []
        if self.episodes:
            for _item_episodes in self.episodes:
                if _item_episodes:
                    _items.append(_item_episodes.to_dict())
            _dict["episodes"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in trailers (list)
        _items = []
        if self.trailers:
            for _item_trailers in self.trailers:
                if _item_trailers:
                    _items.append(_item_trailers.to_dict())
            _dict["trailers"] = _items
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict["type"] = self.type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tag_options (list)
        _items = []
        if self.tag_options:
            for _item_tag_options in self.tag_options:
                if _item_tag_options:
                    _items.append(_item_tag_options.to_dict())
            _dict["tagOptions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in translations (list)
        _items = []
        if self.translations:
            for _item_translations in self.translations:
                if _item_translations:
                    _items.append(_item_translations.to_dict())
            _dict["translations"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SeasonExtendedRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "artwork": (
                    [ArtworkBaseRecord.from_dict(_item) for _item in obj["artwork"]]
                    if obj.get("artwork") is not None
                    else None
                ),
                "companies": (
                    Companies.from_dict(obj["companies"]).model_dump()
                    if obj.get("companies") is not None
                    else None
                ),
                "episodes": (
                    [EpisodeBaseRecord.from_dict(_item) for _item in obj["episodes"]]
                    if obj.get("episodes") is not None
                    else None
                ),
                "id": obj.get("id"),
                "image": obj.get("image"),
                "imageType": obj.get("imageType"),
                "lastUpdated": obj.get("lastUpdated"),
                "name": obj.get("name"),
                "nameTranslations": obj.get("nameTranslations"),
                "number": obj.get("number"),
                "overviewTranslations": obj.get("overviewTranslations"),
                "seriesId": obj.get("seriesId"),
                "trailers": (
                    [Trailer.from_dict(_item) for _item in obj["trailers"]]
                    if obj.get("trailers") is not None
                    else None
                ),
                "type": (
                    SeasonType.from_dict(obj["type"])
                    if obj.get("type") is not None
                    else None
                ),
                "tagOptions": (
                    [TagOption.from_dict(_item) for _item in obj["tagOptions"]]
                    if obj.get("tagOptions") is not None
                    else None
                ),
                "translations": (
                    [Translation.from_dict(_item) for _item in obj["translations"]]
                    if obj.get("translations") is not None
                    else None
                ),
                "year": obj.get("year"),
            }
        )
        return _obj
