name: "\U0001F41E Bug Report"
description: "Riven not working the way it is documented?"
title: "[Bug]: "
labels: ["kind/bug", "status/triage"]
assignees:
  - dreulavelle

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a complete bug report.

  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe what happened, with as much pertinent information as you can. Feel free to use markdown syntax.

        Also, ensure that the issue is not already fixed in the latest release.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Workarounds
      description: |
        Is there a mitigation or workaround that allows users to avoid the issue today?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Attach Error Logs
      description: |
        Please attach logs or error messages that can help in debugging the issue.
      render: 'bash session'
    validations:
      required: true