name: "\U0001F381 Feature Request"
description: "Did you find bugs, errors, or anything that isn't straightforward in the documentation?"
title: "[Feature]: "
labels: ["kind/feature", "status/triage"]
assignees:
  - dreulavelle

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a complete bug report.

        Before submitting your issue, please search [issues](https://github.com/rivenmedia/riven/issues) to ensure this is not a duplicate.

        If the issue is trivial, why not submit a pull request instead?

  - type: dropdown
    attributes:
      label: Issue Kind
      description: |
        What best describes this issue?
      options:
        - "New Feature Request"
        - "Change in current behaviour"
        - "Other"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe the issue, with as much pertinent information as you can. Feel free to use markdown syntax.

    validations:
      required: true

  - type: textarea
    attributes:
      label: Impact
      description: |
        Please describe the motivation for this issue. Describe, as best you can, how this improves or impacts the users of Riven and why this is important.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Workarounds
      description: |
        Is there a mitigation, workaround, or another application that allows users to achieve the same functionality today?
    validations:
      required: true
