# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.modify_list200_response_added import (
    ModifyList200ResponseAdded,
)
from typing import Optional, Set
from typing_extensions import Self


class ModifyList200Response(BaseModel):
    """
    ModifyList200Response
    """  # noqa: E501

    added: Optional[ModifyList200ResponseAdded] = None
    existing: Optional[ModifyList200ResponseAdded] = None
    not_found: Optional[ModifyList200ResponseAdded] = None
    __properties: ClassVar[List[str]] = ["added", "existing", "not_found"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModifyList200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of added
        if self.added:
            _dict["added"] = self.added.to_dict()
        # override the default output from pydantic by calling `to_dict()` of existing
        if self.existing:
            _dict["existing"] = self.existing.to_dict()
        # override the default output from pydantic by calling `to_dict()` of not_found
        if self.not_found:
            _dict["not_found"] = self.not_found.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModifyList200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "added": (
                    ModifyList200ResponseAdded.from_dict(obj["added"])
                    if obj.get("added") is not None
                    else None
                ),
                "existing": (
                    ModifyList200ResponseAdded.from_dict(obj["existing"])
                    if obj.get("existing") is not None
                    else None
                ),
                "not_found": (
                    ModifyList200ResponseAdded.from_dict(obj["not_found"])
                    if obj.get("not_found") is not None
                    else None
                ),
            }
        )
        return _obj
