# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.mdblist.api.sync_api import SyncApi


class TestSyncApi(unittest.TestCase):
    """SyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SyncApi()

    def tearDown(self) -> None:
        pass

    def test_add_or_update_collection(self) -> None:
        """Test case for add_or_update_collection

        Add or Update Collection
        """
        pass

    def test_add_or_update_ratings(self) -> None:
        """Test case for add_or_update_ratings

        Add or Update Ratings
        """
        pass

    def test_add_or_update_watched_history(self) -> None:
        """Test case for add_or_update_watched_history

        Add or Update Watched History
        """
        pass

    def test_remove_collection(self) -> None:
        """Test case for remove_collection

        Remove Collection
        """
        pass

    def test_remove_ratings(self) -> None:
        """Test case for remove_ratings

        Remove Ratings
        """
        pass

    def test_remove_watched_history(self) -> None:
        """Test case for remove_watched_history

        Remove Watched History
        """
        pass

    def test_retrieve_collection(self) -> None:
        """Test case for retrieve_collection

        Retrieve Collection
        """
        pass

    def test_retrieve_last_activities(self) -> None:
        """Test case for retrieve_last_activities

        Retrieve Last Activities
        """
        pass

    def test_retrieve_ratings(self) -> None:
        """Test case for retrieve_ratings

        Retrieve Ratings
        """
        pass

    def test_retrieve_watched_history(self) -> None:
        """Test case for retrieve_watched_history

        Retrieve Watched History
        """
        pass


if __name__ == "__main__":
    unittest.main()
