# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.mdblist.models.modify_list_request_movies_inner import (
    ModifyListRequestMoviesInner,
)


class TestModifyListRequestMoviesInner(unittest.TestCase):
    """ModifyListRequestMoviesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModifyListRequestMoviesInner:
        """Test ModifyListRequestMoviesInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ModifyListRequestMoviesInner`
        """
        model = ModifyListRequestMoviesInner()
        if include_optional:
            return ModifyListRequestMoviesInner(
                tmdb = 1.337,
                imdb = ''
            )
        else:
            return ModifyListRequestMoviesInner(
                tmdb = 1.337,
        )
        """

    def testModifyListRequestMoviesInner(self):
        """Test ModifyListRequestMoviesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
