# coding: utf-8

"""
MDBList API

API service allows you to access information about ratings, votes, streaming services and more  ## API Keys  API key can be generated for free in mdblist.com preferences  ## Pagination  Some methods support pagination 📄   Append a query string like ?limit=`limit`&offset=`offset` to the URL to influence the results.  | Parameter | Type | Value | | --------- | ---- | ----- | | `limit` | integer  | Number of results to return | | `offset` | integer  | Number of results to skip from the beginning  |

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from schemas.mdblist.api.watchlist_api import WatchlistApi


class TestWatchlistApi(unittest.TestCase):
    """WatchlistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WatchlistApi()

    def tearDown(self) -> None:
        pass

    def test_get_watchlist_items(self) -> None:
        """Test case for get_watchlist_items

        Get Watchlist Items
        """
        pass

    def test_modify_watchlist(self) -> None:
        """Test case for modify_watchlist

        Modify Watchlist
        """
        pass


if __name__ == "__main__":
    unittest.main()
